export enum TYPE {
    GET_PRIVATE_TOURS = 'GET_PRIVATE_TOURS',
    GET_PRIVATE_TOURS_SUCCESS = 'GET_PRIVATE_TOURS_SUCCESS',
    DELETE_PRIVATE_TOUR = 'DELETE_PRIVATE_TOUR',
    DELETE_PRIVATE_TOUR_SUCCESS = 'DELETE_PRIVATE_TOUR_SUCCESS',
}
