export enum STATUS {
    ACTIVITING = 'Activing',
    ENDING = 'Ending',
    PENDING = 'Pending',
}

export enum TYPE {
    GET_TOURS = 'GET_TOURS',
    GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS',
    ADD_TOUR = 'ADD_TOUR',
    ADD_TOUR_SUCCESS = 'ADD_TOUR_SUCCESS',
    UPDATE_TOUR = 'UPDATE_TOUR',
    UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS',
    DELETE_TOUR = 'DELETE_TOUR',
    DELETE_TOUR_SUCCESS = 'DELETE_TOUR_SUCCESS',
}
