export const INIT_STATE = [];

export enum TYPE {
    GET_GENDER_USER = 'GET_GENDER_USER',
    GET_GENDER_USER_SUCCESS = 'GET_GENDER_USER_SUCCESS',
    GET_GENDER_AMOUNT_OF_CUSTOMER = 'GET_GENDER_AMOUNT_OF_CUSTOMER',
    GET_GENDER_AMOUNT_OF_CUSTOMER_SUCCESS = 'GET_GENDER_AMOUNT_OF_CUSTOMER_SUCCESS',
    GET_GMV = 'GET_GMV',
    GET_GMV_SUCCESS = 'GET_GMV_SUCCESS',
    GET_BOOKED_CATEGORIES = 'GET_BOOKED_CATEGORIES',
    GET_BOOKED_CATEGORIES_SUCCESS = 'GET_BOOKED_CATEGORIES_SUCCESS',
}
